# Generated by Django 3.2.6 on 2021-08-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecalendar', '0003_event_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='guest_nmbr',
            new_name='nbre_siege',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='requester',
        ),
        migrations.AddField(
            model_name='event',
            name='disposition_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='salle_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='salle_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
